### 0) imports

In [1]:
import numpy as np
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, GroupKFold, StratifiedKFold, TimeSeriesSplit
from sklearn.linear_model import Lasso
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import root_mean_squared_error as rmse
from sklearn.metrics import r2_score
import shap
from sklearn.linear_model import ElasticNet
import optuna

### 1) Answer the questions from the introduction

#### What is leave-one-out? Provide limitations and strengths

LeaveOneOut (или LOO) — это простая перекрестная проверка. Каждый обучающий набор создается путем взятия всех образцов, кроме одного, причем тестовый набор — это сам исключенный образец. \
Преимущества:
- Эта процедура перекрестной проверки не приводит к большим потерям данных, поскольку из обучающего набора удаляется только один образец
- Максимальное использование данных

Недостатки:
- С точки зрения точности, метод часто приводит к высокой дисперсии в качестве оценки ошибки теста
- Огромные вычислительные данные
- Проблема утечки

#### How do Grid Search, Randomized Grid Search, and Bayesian optimization work?

Grid Search:
- Заранее определяем интересующие нас параметры и затем уже сам алгоритм строит из них сетку

Randomized Grid Search:
- Этот метод случайным образом выбирает точки из заданного интервала значений

Bayesian optimization work:
- Это метод, который учится на своих прошлых значениях, каждая следующая попытка основывается на результатах предыдущих.

#### Explain classification of feature selection methods

Filter Methods:
- Оценивают каждый признак независимо от модели. Они смотрят на статистические свойства данных (корреляция, вариативность)

Wrapper Methods:
- Они перебирают разные подмножества признаков, обучают модель и находят лучший набор именно для данной модели

Embedded Methods:
- Отбор происходит прямо во время обучения модели. Модель сама решает, какие признаки важны

#### Explain how Pearson and Chi2 work

- Pearson измеряет силу линейной зависимости между двумя непрерывными переменными (от -1 до 1)
- Chi2 проверяет, есть ли зависимость между признаком и целевым классом. Если распределение признака одинаково для всех классов, то признак бесполезен (независим).

#### Explain how Lasso works

К функции потерь (ошибке) модели добавляется штраф, равный сумме абсолютных значений коэффициентов, а так он совпадает с линейной регрессией

#### Explain what permutation significance is

Берем один признак и случайным образом перемешиваем (переставляем) его значения в тестовой выборке. Если после порчи признака точность модели рухнула — значит, признак был критически важен. Если точность почти не изменилась — признак бесполезен.

#### Become familiar with SHAP

Метод перебирает все возможные комбинации признаков и оценивает, как добавление конкретного признака $X$ меняет предсказание по сравнению со средним значением

### 2) Introduction

In [2]:
data = pd.read_json('../datasets/train.json')
data['created'] = pd.to_datetime(data['created'])
data.sort_values(by='created', ascending=True, inplace=True)
data.reset_index(inplace=True)
df = pd.DataFrame()

In [3]:
data = data[(data['bathrooms'] >= data['bathrooms'].quantile(0.01)) & (data['bathrooms'] <= data['bathrooms'].quantile(0.99))]
data = data[(data['bedrooms'] >= data['bedrooms'].quantile(0.01)) & (data['bedrooms'] <= data['bedrooms'].quantile(0.99))]
data = data[(data['price'] >= data['price'].quantile(0.01)) & (data['price'] <= data['price'].quantile(0.99))]

In [4]:
data['interest_level'] = data['interest_level'].map({'low':0, 'medium':1, 'high':2})

In [5]:
all_features = []
for index, row in data.iterrows():
    for feature in row['features']:
        features = feature.replace('[', '').replace(']', '').replace("'", '').replace('"', '').replace(' ', '')
        all_features.append(features)

In [6]:
all_features = Counter(all_features).most_common(20)
feature_list = [feature for feature, _ in all_features]

In [7]:
df['bathrooms'] = data['bathrooms']
df['bedrooms'] = data['bedrooms']
df['interest_level'] = data['interest_level']
for feature in feature_list:
    df[feature] = data['features'].apply(lambda x: 1 if feature in x else 0)

### 3) Implement the next methods

In [8]:
def random_split_train_test(data, test_size, seed=21):
    np.random.seed(seed)
    data = np.random.permutation(data)
    len_test = int(round(len(data) * test_size))
    train = data[len_test:]
    test = data[:len_test]
    return train, test

In [9]:
def random_split_train_valid_test(data, test_size, validation_size, seed=21):
    np.random.seed(seed)
    validation_size = validation_size / (1 - test_size)
    train_valid, test = random_split_train_test(data, test_size)
    train, valid = random_split_train_test(train_valid, validation_size)
    return train, valid, test

In [10]:
def split_train_test(data, date_column, date_split):
    data_sorted = data.sort_values(date_column)
    train_mask = data_sorted[date_column] < date_split
    test_mask = data_sorted[date_column] >= date_split
    train = data_sorted[train_mask]
    test = data_sorted[test_mask]
    return train, test

In [11]:
def split_train_valid_test(data, date_column, date_valid, date_test):
    data_sorted = data.sort_values(date_column)
    train = data_sorted[data_sorted[date_column] < date_valid]
    valid = data_sorted[(data_sorted[date_column] >= date_valid) & 
                        (data_sorted[date_column] < date_test)]
    test = data_sorted[data_sorted[date_column] >= date_test]
    return train, valid, test

### 4) Implement the next cross-validation methods

In [12]:
class MyKFold:
    def __init__(self, k=5):
        self.n_splits = k

    def _iter_test_indices(self, X):
        n_samples = len(X)
        indices = np.arange(n_samples)
        fold_sizes = np.full(self.n_splits, n_samples // self.n_splits, dtype=int)
        fold_sizes[:n_samples % self.n_splits] += 1
        current = 0
        for fold_size in fold_sizes:
            start, stop = current, current + fold_size
            yield indices[start:stop]
            current = stop
            
    def split(self, X):
        n_samples = len(X)
        indices = np.arange(n_samples)
        for test_index in self._iter_test_indices(X):
            train_index = np.setdiff1d(indices, test_index)
            yield train_index, test_index

In [13]:
class MyGroupKFold:
    def __init__(self, k=5):
        self.n_splits = k

    def _iter_test_indices(self, X, group_field):
        unique_groups = np.unique(group_field)
        fold_groups = np.array_split(unique_groups, self.n_splits)
        for fold_group in fold_groups:
            test_index = np.where(np.isin(group_field, fold_group))
            yield test_index
            
    def split(self, X, group_field=None):
        n_samples = len(X)
        indices = np.arange(n_samples)
        for test_index in self._iter_test_indices(X, group_field):
            train_index = np.setdiff1d(indices, test_index)
            yield train_index, test_index

In [14]:
class MyStratifiedKFold:
    def __init__(self, k=5):
        self.n_splits = k

    def _iter_test_indices(self, X, stratify_field):
        classes = np.unique(stratify_field)
        classes_indices = [np.where(stratify_field == c)[0] for c in classes]
        fold_classes = [np.array_split(idx, self.n_splits) for idx in classes_indices]
        for i in range(self.n_splits):
            test_index = np.concatenate([fold_class[i] for fold_class in fold_classes])
            yield test_index

    def split(self, X, stratify_field=None):
        n_samples = len(X)
        indices = np.arange(n_samples)
        for test_index in self._iter_test_indices(X, stratify_field):
            train_index = np.setdiff1d(indices, test_index)
            yield train_index, test_index

In [15]:
class MyTimeSeriesSplit:
    def __init__(self, k=5):
        self.n_splits = k

    def _iter_test_indices(self, X, date_field):
        date_field = np.array(date_field)
        sorted_indices = np.argsort(date_field)
        n_samples = len(X)
        test_size = n_samples // (self.n_splits + 1)
        
        for i in range(1, self.n_splits + 1):
            split_point = i * test_size
            test_end = split_point + test_size
            if i == self.n_splits:
                test_end = n_samples
            yield sorted_indices[split_point:test_end]

    def split(self, X, date_field=None):
        n_samples = len(X)
        date_field = np.array(date_field)
        sorted_indices = np.argsort(date_field)
        
        for test_index in self._iter_test_indices(X, date_field):
            first_test_pos = np.where(sorted_indices == test_index[0])[0][0]
            train_index = sorted_indices[:first_test_pos]
            
            yield train_index, test_index

### 5) Cross-validation comparison

In [16]:
X = df.copy()
y = data['interest_level']

In [17]:
my_kf = MyKFold()
for i, (train_index, test_index) in enumerate(my_kf.split(X)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[ 9512  9513  9514 ... 47555 47556 47557]
  Test:  index=[   0    1    2 ... 9509 9510 9511]
Fold 1:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[ 9512  9513  9514 ... 19021 19022 19023]
Fold 2:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[19024 19025 19026 ... 28533 28534 28535]
Fold 3:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[28536 28537 28538 ... 38044 38045 38046]
Fold 4:
  Train: index=[    0     1     2 ... 38044 38045 38046]
  Test:  index=[38047 38048 38049 ... 47555 47556 47557]

In [18]:
sk_kf = KFold()
for i, (train_index, test_index) in enumerate(sk_kf.split(X)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[ 9512  9513  9514 ... 47555 47556 47557]
  Test:  index=[   0    1    2 ... 9509 9510 9511]
Fold 1:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[ 9512  9513  9514 ... 19021 19022 19023]
Fold 2:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[19024 19025 19026 ... 28533 28534 28535]
Fold 3:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[28536 28537 28538 ... 38044 38045 38046]
Fold 4:
  Train: index=[    0     1     2 ... 38044 38045 38046]
  Test:  index=[38047 38048 38049 ... 47555 47556 47557]

In [19]:
groups = data['manager_id'].values

In [20]:
my_group_kfold = MyGroupKFold()
for i, (train_index, test_index) in enumerate(my_group_kfold.split(X, group_field=groups)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}, group={groups[train_index]}")
    print(f"  Test:  index={test_index}, group={groups[test_index]}")

Fold 0:
  Train: index=[    0     1     2 ... 47555 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=(array([    3,    13,    14, ..., 47548, 47552, 47553], shape=(9245,)),), group=['262471a6a678adb458e879b092b23b4b' '044573b60ce5da02f510e49f086707ec'
 '1a79c79b0366512deaa5053ae501964b' ... '25d4ea3f8ec14332bcf177e416c6747d'
 '0bafd514443193d057e8a60e45cb7ea6' '0bafd514443193d057e8a60e45cb7ea6']
Fold 1:
  Train: index=[    0     3     4 ... 47554 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '262471a6a678adb458e879b092b23b4b'
 '7c5e4fc025b70c6540d6b0e06716b9dd' ... '6c2a16187e6855c132bb496b875a4ef7'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=(array([    1,     2,     5, ..., 47519, 47520, 47555], shape=(9618,)),), group=['3b630ec9cb6eee53b92cfac7f42e3bf4' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '4ccafba721db54b92d97c0af85847c02' ... '4bdc3d8c1aaa90d997ce2cb77680679b'
 '4bdc3d8c1aaa90d997ce2cb77680679b' '634f618895493a04f7722f113a89947b']
Fold 2:
  Train: index=[    0     1     2 ... 47552 47553 47555], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '0bafd514443193d057e8a60e45cb7ea6'
 '0bafd514443193d057e8a60e45cb7ea6' '634f618895493a04f7722f113a89947b']
  Test:  index=(array([    4,     6,    10, ..., 47554, 47556, 47557], shape=(8661,)),), group=['7c5e4fc025b70c6540d6b0e06716b9dd' '92343a6bd78f22d6968260f85ee79c2d'
 '91a276fdb4c7ae5ff56fd0884b5121db' ... '6c2a16187e6855c132bb496b875a4ef7'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
Fold 3:
  Train: index=[    0     1     2 ... 47555 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=(array([   21,    38,    47, ..., 47546, 47547, 47549], shape=(8920,)),), group=['a2f8cca8b11e7f91011ba1a62088dbfe' '9fb89dd6389267ed37abbd8d78efcd6f'
 'b07d2cbfb0e81ce4c681dcd87f2fc849' ... 'b7de4cb395920136663132057fa89d84'
 'b7de4cb395920136663132057fa89d84' 'b7de4cb395920136663132057fa89d84']
Fold 4:
  Train: index=[    1     2     3 ... 47555 47556 47557], group=['3b630ec9cb6eee53b92cfac7f42e3bf4' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '262471a6a678adb458e879b092b23b4b' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=(array([    0,     7,     9, ..., 47527, 47550, 47551], shape=(11114,)),), group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' 'd24abc331d8b47f73a369795690c010a'
 'f1e4ee51ab6974e8f9b71c25eced35b0' ... 'e6472c7237327dd3903b3d6f6a94515a'
 'f5e44ef976867c828130d0e6e6cdbda5' 'f1e497a5f59e1c3f015a2e46632af940']

In [21]:
sk_group_kfold = GroupKFold()
for i, (train_index, test_index) in enumerate(sk_group_kfold.split(X, groups=groups)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}, group={groups[train_index]}")
    print(f"  Test:  index={test_index}, group={groups[test_index]}")

Fold 0:
  Train: index=[    0     1     2 ... 47555 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=[   12    16    18 ... 47524 47527 47550], group=['38e613cd90ba43943211be10168ee175' 'e6472c7237327dd3903b3d6f6a94515a'
 'e6472c7237327dd3903b3d6f6a94515a' ... 'babf967aeb47132007ac2dd76c204d49'
 'e6472c7237327dd3903b3d6f6a94515a' 'f5e44ef976867c828130d0e6e6cdbda5']
Fold 1:
  Train: index=[    0     4     5 ... 47553 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '7c5e4fc025b70c6540d6b0e06716b9dd'
 '4ccafba721db54b92d97c0af85847c02' ... '0bafd514443193d057e8a60e45cb7ea6'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=[    1     2     3 ... 47548 47554 47555], group=['3b630ec9cb6eee53b92cfac7f42e3bf4' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '262471a6a678adb458e879b092b23b4b' ... '25d4ea3f8ec14332bcf177e416c6747d'
 '6c2a16187e6855c132bb496b875a4ef7' '634f618895493a04f7722f113a89947b']
Fold 2:
  Train: index=[    1     2     3 ... 47555 47556 47557], group=['3b630ec9cb6eee53b92cfac7f42e3bf4' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '262471a6a678adb458e879b092b23b4b' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=[    0     9    11 ... 47522 47523 47551], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' 'f1e4ee51ab6974e8f9b71c25eced35b0'
 '8b53ccf4338806ab1be3dd0267711649' ... '0ed22c41834a89b0905341a4883bcfd8'
 'c0999793234144881eeec9cecb1c4b8f' 'f1e497a5f59e1c3f015a2e46632af940']
Fold 3:
  Train: index=[    0     1     2 ... 47553 47554 47555], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '0bafd514443193d057e8a60e45cb7ea6'
 '6c2a16187e6855c132bb496b875a4ef7' '634f618895493a04f7722f113a89947b']
  Test:  index=[    8    10    13 ... 47549 47556 47557], group=['456089ec27510652ee3878a399ed56e0' '91a276fdb4c7ae5ff56fd0884b5121db'
 '044573b60ce5da02f510e49f086707ec' ... 'b7de4cb395920136663132057fa89d84'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
Fold 4:
  Train: index=[    0     1     2 ... 47555 47556 47557], group=['f07272f8ceb99db4c1a7cbbd9ae7b75b' '3b630ec9cb6eee53b92cfac7f42e3bf4'
 '3b630ec9cb6eee53b92cfac7f42e3bf4' ... '634f618895493a04f7722f113a89947b'
 '699c325b818541f314b691b76f3238d7' '699c325b818541f314b691b76f3238d7']
  Test:  index=[    4     5     6 ... 47529 47552 47553], group=['7c5e4fc025b70c6540d6b0e06716b9dd' '4ccafba721db54b92d97c0af85847c02'
 '92343a6bd78f22d6968260f85ee79c2d' ... '84a317f6bce6e3c05dec6fb070dd7e0b'
 '0bafd514443193d057e8a60e45cb7ea6' '0bafd514443193d057e8a60e45cb7ea6']

In [22]:
my_skf = MyStratifiedKFold()
for i, (train_index, test_index) in enumerate(my_skf.split(X, stratify_field=y)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[ 9125  9131  9140 ... 47555 47556 47557]
  Test:  index=[   5    6    7 ... 9114 9117 9119]
Fold 1:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[ 9467  9469  9471 ... 18611 18612 18665]
Fold 2:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[19280 19281 19282 ... 27557 27563 27569]
Fold 3:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[28803 28804 28806 ... 37032 37034 37075]
Fold 4:
  Train: index=[    0     1     2 ... 38289 38290 38293]
  Test:  index=[38294 38295 38296 ... 47504 47512 47513]

In [23]:
sk_skf = StratifiedKFold()
for i, (train_index, test_index) in enumerate(sk_skf.split(X, y)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[ 9125  9131  9140 ... 47555 47556 47557]
  Test:  index=[   0    1    2 ... 9700 9703 9707]
Fold 1:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[ 9125  9131  9140 ... 19273 19274 19275]
Fold 2:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[18592 18593 18597 ... 28800 28801 28802]
Fold 3:
  Train: index=[    0     1     2 ... 47555 47556 47557]
  Test:  index=[27578 27596 27610 ... 38289 38290 38293]
Fold 4:
  Train: index=[    0     1     2 ... 38289 38290 38293]
  Test:  index=[37115 37120 37130 ... 47555 47556 47557]

In [24]:
my_tscv = MyTimeSeriesSplit()
for i, (train_index, test_index) in enumerate(my_tscv.split(X, date_field=data['created'])):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[   0    1    2 ... 7923 7924 7925]
  Test:  index=[ 7926  7927  7928 ... 15849 15850 15851]
Fold 1:
  Train: index=[    0     1     2 ... 15849 15850 15851]
  Test:  index=[15852 15853 15854 ... 23775 23776 23777]
Fold 2:
  Train: index=[    0     1     2 ... 23775 23776 23777]
  Test:  index=[23778 23779 23780 ... 31701 31702 31703]
Fold 3:
  Train: index=[    0     1     2 ... 31701 31702 31703]
  Test:  index=[31704 31705 31706 ... 39627 39628 39629]
Fold 4:
  Train: index=[    0     1     2 ... 39627 39628 39629]
  Test:  index=[39630 39631 39632 ... 47555 47556 47557]

In [25]:
tscv = TimeSeriesSplit()
for i, (train_index, test_index) in enumerate(tscv.split(X, data['created'])):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

Fold 0:
  Train: index=[   0    1    2 ... 7925 7926 7927]
  Test:  index=[ 7928  7929  7930 ... 15851 15852 15853]
Fold 1:
  Train: index=[    0     1     2 ... 15851 15852 15853]
  Test:  index=[15854 15855 15856 ... 23777 23778 23779]
Fold 2:
  Train: index=[    0     1     2 ... 23777 23778 23779]
  Test:  index=[23780 23781 23782 ... 31703 31704 31705]
Fold 3:
  Train: index=[    0     1     2 ... 31703 31704 31705]
  Test:  index=[31706 31707 31708 ... 39629 39630 39631]
Fold 4:
  Train: index=[    0     1     2 ... 39629 39630 39631]
  Test:  index=[39632 39633 39634 ... 47555 47556 47557]

Для нашего набора методы будут не сильно отличаться, поэтому в данном случае можно выбрать KFold, как лучший метод перекрестной проверки

### 6) Feature Selection

In [26]:
X_train, X_valid, X_test = random_split_train_valid_test(X, 0.2, 0.2)
y_train, y_valid, y_test = random_split_train_valid_test(data['price'], 0.2, 0.2)

In [27]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

In [28]:
lasso = Lasso(alpha=0.1)
lasso.fit(X_train_scaled, y_train)

Lasso(alpha=0.1)

In [29]:
features = pd.DataFrame({'Name': df.columns,'Importance': np.abs(lasso.coef_)})
features.sort_values(by='Importance', inplace=True, ascending=False)
features

                 Name   Importance
0           bathrooms  3055.740653
1            bedrooms  1797.801685
2      interest_level   859.167642
7             Doorman   573.872676
8          Dishwasher   161.790838
22            Terrace   118.120670
3            Elevator   104.287461
12            Pre-War    55.825789
18            Balcony    19.745967
4      HardwoodFloors     0.000000
5         CatsAllowed     0.000000
6         DogsAllowed     0.000000
11      FitnessCenter     0.000000
10  LaundryinBuilding     0.000000
9               NoFee     0.000000
14           RoofDeck     0.000000
13      LaundryinUnit     0.000000
16         DiningRoom     0.000000
15       OutdoorSpace     0.000000
17  HighSpeedInternet     0.000000
19       SwimmingPool     0.000000
20  LaundryInBuilding     0.000000
21    NewConstruction     0.000000

In [30]:
result_MAE = pd.DataFrame(columns=['model', 'train', 'valid', 'test'])
result_RMSE = pd.DataFrame(columns=['model', 'train', 'valid', 'test'])
result_R2 = pd.DataFrame(columns=['model', 'train', 'valid', 'test'])

In [31]:
y_pred_train = lasso.predict(X_train_scaled)
y_pred_valid = lasso.predict(X_valid_scaled)
y_pred_test = lasso.predict(X_test_scaled)

In [32]:
X_train_scaled_top_10_features = pd.DataFrame()
X_valid_scaled_top_10_features = pd.DataFrame()
X_test_scaled_top_10_features = pd.DataFrame()
indices = features.head(10).index
X_train_scaled_top_10_features = X_train_scaled[:,indices]
X_valid_scaled_top_10_features = X_valid_scaled[:,indices]
X_test_scaled_top_10_features = X_test_scaled[:,indices]

In [33]:
lasso.fit(X_train_scaled_top_10_features, y_train)
y_pred_train_top_10_features = lasso.predict(X_train_scaled_top_10_features)
y_pred_valid_top_10_features = lasso.predict(X_valid_scaled_top_10_features)
y_pred_test_top_10_features = lasso.predict(X_test_scaled_top_10_features)

In [34]:
result_MAE.loc[len(result_MAE)] = ['Lasso MinMaxScaler', mae(y_train, y_pred_train), mae(y_valid, y_pred_valid), mae(y_test, y_pred_test)]
result_RMSE.loc[len(result_RMSE)] = ['Lasso MinMaxScaler', rmse(y_train, y_pred_train), rmse(y_valid, y_pred_valid), rmse(y_test, y_pred_test)]
result_R2.loc[len(result_R2)] = ['Lasso MinMaxScaler', r2_score(y_train, y_pred_train), r2_score(y_valid, y_pred_valid), r2_score(y_test, y_pred_test)]

In [35]:
result_MAE.loc[len(result_MAE)] = ['Lasso top10 MinMaxScaler', mae(y_train, y_pred_train_top_10_features), mae(y_valid, y_pred_valid_top_10_features), mae(y_test, y_pred_test_top_10_features)]
result_RMSE.loc[len(result_RMSE)] = ['Lasso top10 MinMaxScaler', rmse(y_train, y_pred_train_top_10_features), rmse(y_valid, y_pred_valid_top_10_features), rmse(y_test, y_pred_test_top_10_features)]
result_R2.loc[len(result_R2)] = ['Lasso top10 MinMaxScaler', r2_score(y_train, y_pred_train_top_10_features), r2_score(y_valid, y_pred_valid_top_10_features), r2_score(y_test, y_pred_test_top_10_features)]

In [36]:
result_MAE

                      model       train       valid        test
0        Lasso MinMaxScaler  668.672518  658.821751  665.124980
1  Lasso top10 MinMaxScaler  668.672709  658.822143  665.125393

In [37]:
result_RMSE

                      model       train       valid        test
0        Lasso MinMaxScaler  939.338320  914.957220  932.435435
1  Lasso top10 MinMaxScaler  939.338309  914.957361  932.435674

In [38]:
result_R2

                      model    train     valid      test
0        Lasso MinMaxScaler  0.57827  0.580479  0.594119
1  Lasso top10 MinMaxScaler  0.57827  0.580478  0.594118

In [39]:
def feature_selection(X, y):
    data = X.loc[:, X.std() > 0]
    corr = data.corrwith(y).abs()
    nan = data.isnull().mean()
    final_score = (1 - corr) + nan
    names_top_10 = final_score.sort_values().head(10).index.to_list()
    indices = [list(X.columns).index(name) for name in names_top_10]
    return indices

In [40]:
indices = feature_selection(X, data['price'])

In [41]:
X_train_scaled_top_10_features = X_train_scaled[:,indices]
X_valid_scaled_top_10_features = X_valid_scaled[:,indices]
X_test_scaled_top_10_features = X_test_scaled[:,indices]

In [42]:
lasso.fit(X_train_scaled_top_10_features, y_train)
y_pred_train_top_10_features = lasso.predict(X_train_scaled_top_10_features)
y_pred_valid_top_10_features = lasso.predict(X_valid_scaled_top_10_features)
y_pred_test_top_10_features = lasso.predict(X_test_scaled_top_10_features)

In [43]:
result_MAE.loc[len(result_MAE)] = ['Lasso top10_selection MinMaxScaler', mae(y_train, y_pred_train_top_10_features), mae(y_valid, y_pred_valid_top_10_features), mae(y_test, y_pred_test_top_10_features)]
result_RMSE.loc[len(result_RMSE)] = ['Lasso top10_selection MinMaxScaler', rmse(y_train, y_pred_train_top_10_features), rmse(y_valid, y_pred_valid_top_10_features), rmse(y_test, y_pred_test_top_10_features)]
result_R2.loc[len(result_R2)] = ['Lasso top10_selection MinMaxScaler', r2_score(y_train, y_pred_train_top_10_features), r2_score(y_valid, y_pred_valid_top_10_features), r2_score(y_test, y_pred_test_top_10_features)]

In [44]:
result_MAE

                                model       train       valid        test
0                  Lasso MinMaxScaler  668.672518  658.821751  665.124980
1            Lasso top10 MinMaxScaler  668.672709  658.822143  665.125393
2  Lasso top10_selection MinMaxScaler  668.672775  658.822322  665.125238

In [45]:
result_RMSE

                                model       train       valid        test
0                  Lasso MinMaxScaler  939.338320  914.957220  932.435435
1            Lasso top10 MinMaxScaler  939.338309  914.957361  932.435674
2  Lasso top10_selection MinMaxScaler  939.338320  914.957404  932.435501

In [46]:
result_R2

                                model    train     valid      test
0                  Lasso MinMaxScaler  0.57827  0.580479  0.594119
1            Lasso top10 MinMaxScaler  0.57827  0.580478  0.594118
2  Lasso top10_selection MinMaxScaler  0.57827  0.580478  0.594119

In [47]:
def my_permutation_importance(model, X, y, seed=21):
    base_score = r2_score(y, model.predict(X))
    importances = []
    for i in range(X.shape[1]):
        X_copy = X.copy()
        np.random.seed(seed)
        np.random.shuffle(X_copy[:, i])
        new_score = r2_score(y, model.predict(X_copy))
        importances.append(base_score - new_score)
    top_10_indices = np.argsort(importances)[-10:][::-1]
    return top_10_indices

In [48]:
lasso.fit(X_train_scaled, y_train)
indices = my_permutation_importance(lasso, X_train_scaled, y_train)

In [49]:
X_train_scaled_top_10_features = X_train_scaled[:,indices]
X_valid_scaled_top_10_features = X_valid_scaled[:,indices]
X_test_scaled_top_10_features = X_test_scaled[:,indices]

In [50]:
lasso.fit(X_train_scaled_top_10_features, y_train)
y_pred_train_top_10_features = lasso.predict(X_train_scaled_top_10_features)
y_pred_valid_top_10_features = lasso.predict(X_valid_scaled_top_10_features)
y_pred_test_top_10_features = lasso.predict(X_test_scaled_top_10_features)

In [51]:
result_MAE.loc[len(result_MAE)] = ['Lasso permutation MinMaxScaler', mae(y_train, y_pred_train_top_10_features), mae(y_valid, y_pred_valid_top_10_features), mae(y_test, y_pred_test_top_10_features)]
result_RMSE.loc[len(result_RMSE)] = ['Lasso permutation MinMaxScaler', rmse(y_train, y_pred_train_top_10_features), rmse(y_valid, y_pred_valid_top_10_features), rmse(y_test, y_pred_test_top_10_features)]
result_R2.loc[len(result_R2)] = ['Lasso permutation MinMaxScaler', r2_score(y_train, y_pred_train_top_10_features), r2_score(y_valid, y_pred_valid_top_10_features), r2_score(y_test, y_pred_test_top_10_features)]

In [52]:
result_MAE

                                model       train       valid        test
0                  Lasso MinMaxScaler  668.672518  658.821751  665.124980
1            Lasso top10 MinMaxScaler  668.672709  658.822143  665.125393
2  Lasso top10_selection MinMaxScaler  668.672775  658.822322  665.125238
3      Lasso permutation MinMaxScaler  668.673573  658.823407  665.126185

In [53]:
result_RMSE

                                model       train       valid        test
0                  Lasso MinMaxScaler  939.338320  914.957220  932.435435
1            Lasso top10 MinMaxScaler  939.338309  914.957361  932.435674
2  Lasso top10_selection MinMaxScaler  939.338320  914.957404  932.435501
3      Lasso permutation MinMaxScaler  939.338313  914.957407  932.435820

In [54]:
result_R2

                                model    train     valid      test
0                  Lasso MinMaxScaler  0.57827  0.580479  0.594119
1            Lasso top10 MinMaxScaler  0.57827  0.580478  0.594118
2  Lasso top10_selection MinMaxScaler  0.57827  0.580478  0.594119
3      Lasso permutation MinMaxScaler  0.57827  0.580478  0.594118

In [55]:
lasso.fit(X_train_scaled, y_train)
explainer = shap.LinearExplainer(lasso, X_train_scaled)

In [56]:
shap_values = explainer.shap_values(X_train_scaled)
shap_values = np.abs(shap_values).mean(axis=0)

In [57]:
shap_table = pd.DataFrame({'features':df.columns, 'shap_value':shap_values}) 
shap_table.sort_values(by='shap_value', inplace=True, ascending=False)
shap_table

             features  shap_value
0           bathrooms  449.719908
1            bedrooms  404.962170
7             Doorman  272.528582
2      interest_level  226.151327
8          Dishwasher   80.359027
3            Elevator   52.282761
12            Pre-War   17.789789
22            Terrace    9.595866
18            Balcony    2.391564
4      HardwoodFloors    0.000000
5         CatsAllowed    0.000000
6         DogsAllowed    0.000000
11      FitnessCenter    0.000000
10  LaundryinBuilding    0.000000
9               NoFee    0.000000
14           RoofDeck    0.000000
13      LaundryinUnit    0.000000
16         DiningRoom    0.000000
15       OutdoorSpace    0.000000
17  HighSpeedInternet    0.000000
19       SwimmingPool    0.000000
20  LaundryInBuilding    0.000000
21    NewConstruction    0.000000

In [58]:
indices = shap_table.head(10).index
X_train_scaled_top_10_features = X_train_scaled[:,indices]
X_valid_scaled_top_10_features = X_valid_scaled[:,indices]
X_test_scaled_top_10_features = X_test_scaled[:,indices]

In [59]:
lasso.fit(X_train_scaled_top_10_features, y_train)
y_pred_train_top_10_features = lasso.predict(X_train_scaled_top_10_features)
y_pred_valid_top_10_features = lasso.predict(X_valid_scaled_top_10_features)
y_pred_test_top_10_features = lasso.predict(X_test_scaled_top_10_features)

In [60]:
result_MAE.loc[len(result_MAE)] = ['Lasso shap MinMaxScaler', mae(y_train, y_pred_train_top_10_features), mae(y_valid, y_pred_valid_top_10_features), mae(y_test, y_pred_test_top_10_features)]
result_RMSE.loc[len(result_RMSE)] = ['Lasso shap MinMaxScaler', rmse(y_train, y_pred_train_top_10_features), rmse(y_valid, y_pred_valid_top_10_features), rmse(y_test, y_pred_test_top_10_features)]
result_R2.loc[len(result_R2)] = ['Lasso shap MinMaxScaler', r2_score(y_train, y_pred_train_top_10_features), r2_score(y_valid, y_pred_valid_top_10_features), r2_score(y_test, y_pred_test_top_10_features)]

In [61]:
result_MAE

                                model       train       valid        test
0                  Lasso MinMaxScaler  668.672518  658.821751  665.124980
1            Lasso top10 MinMaxScaler  668.672709  658.822143  665.125393
2  Lasso top10_selection MinMaxScaler  668.672775  658.822322  665.125238
3      Lasso permutation MinMaxScaler  668.673573  658.823407  665.126185
4             Lasso shap MinMaxScaler  668.673568  658.823399  665.126180

In [62]:
result_RMSE

                                model       train       valid        test
0                  Lasso MinMaxScaler  939.338320  914.957220  932.435435
1            Lasso top10 MinMaxScaler  939.338309  914.957361  932.435674
2  Lasso top10_selection MinMaxScaler  939.338320  914.957404  932.435501
3      Lasso permutation MinMaxScaler  939.338313  914.957407  932.435820
4             Lasso shap MinMaxScaler  939.338313  914.957404  932.435822

In [63]:
result_R2

                                model    train     valid      test
0                  Lasso MinMaxScaler  0.57827  0.580479  0.594119
1            Lasso top10 MinMaxScaler  0.57827  0.580478  0.594118
2  Lasso top10_selection MinMaxScaler  0.57827  0.580478  0.594119
3      Lasso permutation MinMaxScaler  0.57827  0.580478  0.594118
4             Lasso shap MinMaxScaler  0.57827  0.580478  0.594118

### 7) Hyperparameter optimization

In [64]:
class MyGridSearchCV:
    def __init__(self, param_grid, cv):
        self.param_grid = param_grid
        self.cv = cv
        self.best_score = -float('inf')
        self.best_alpha = None
        self.best_l1_ratio = None

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)

        kf = MyKFold(k=self.cv)

        for alpha in self.param_grid[0]:
            for l1_ratio in self.param_grid[1]:
                model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)

                scores = []
                for train_index, test_index in kf.split(X):
                    X_train, X_test = X[train_index], X[test_index]
                    y_train, y_test = y[train_index], y[test_index]

                    model.fit(X_train, y_train)
                    y_pred = model.predict(X_test)

                    scores.append(r2_score(y_test, y_pred))

                avg_score = np.mean(scores)

                if avg_score > self.best_score:
                    self.best_score = avg_score
                    self.best_alpha = alpha
                    self.best_l1_ratio = l1_ratio
                    
    def best_params_(self):
        return self.best_alpha, self.best_l1_ratio

    def best_score_(self):
        return self.best_score

In [65]:
class MyRandomizedSearchCV(MyGridSearchCV):
    def __init__(self, param_grid, cv, n_iter):
        super().__init__(param_grid, cv)
        self.n_iter = n_iter

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        kf = MyKFold(k=self.cv)

        for i in range(self.n_iter):
            alpha = np.random.choice(self.param_grid[0])
            l1_ratio = np.random.choice(self.param_grid[1])

            model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)
            scores = []
            
            for train_index, test_index in kf.split(X):
                X_train, X_test = X[train_index], X[test_index]
                y_train, y_test = y[train_index], y[test_index]

                model.fit(X_train, y_train)
                y_pred = model.predict(X_test)
                scores.append(r2_score(y_test, y_pred))

            avg_score = np.mean(scores)

            if avg_score > self.best_score:
                self.best_score = avg_score
                self.best_alpha = alpha
                self.best_l1_ratio = l1_ratio

In [66]:
param_grid = [[0.01, 0.1, 1, 10], 
              [0.1, 0.3, 0.5, 0.7, 0.9]]

In [67]:
scaler.fit_transform(X)

array([[0.  , 0.25, 1.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , ..., 0.  , 0.  , 0.  ],
       [0.5 , 0.75, 1.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.25, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ]], shape=(47558, 23))

In [68]:
my_grid_search = MyGridSearchCV(param_grid, 5)
my_grid_search.fit(X, data['price'])
alpha, l1_ratio = my_grid_search.best_params_()
print(my_grid_search.best_score_())

0.580941146604333

In [69]:
elastic = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)
elastic.fit(X_train_scaled, y_train)

ElasticNet(alpha=0.01, l1_ratio=0.9)

In [70]:
y_pred_train = elastic.predict(X_train_scaled)
y_pred_valid = elastic.predict(X_valid_scaled)
y_pred_test = elastic.predict(X_test_scaled)

In [71]:
result_MAE.loc[len(result_MAE)] = ['ElasticNet GridSearch MinMaxScaler', mae(y_train, y_pred_train), mae(y_valid, y_pred_valid), mae(y_test, y_pred_test)]
result_RMSE.loc[len(result_RMSE)] = ['ElasticNet GridSearch MinMaxScaler', rmse(y_train, y_pred_train), rmse(y_valid, y_pred_valid), rmse(y_test, y_pred_test)]
result_R2.loc[len(result_R2)] = ['ElasticNet GridSearch MinMaxScaler', r2_score(y_train, y_pred_train), r2_score(y_valid, y_pred_valid), r2_score(y_test, y_pred_test)]

In [72]:
param_grid = [[0.0001, 0.001, 0.01, 0.1], 
              [0.1, 0.3, 0.5, 0.7, 0.9]]

In [73]:
my_random_search = MyRandomizedSearchCV(param_grid, 5, 5)
my_random_search.fit(X, data['price'])
alpha, l1_ratio = my_random_search.best_params_()
print(my_grid_search.best_score_())

0.580941146604333

In [74]:
elastic = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)
elastic.fit(X_train_scaled, y_train)

ElasticNet(alpha=np.float64(0.001), l1_ratio=np.float64(0.7))

In [75]:
y_pred_train = elastic.predict(X_train_scaled)
y_pred_valid = elastic.predict(X_valid_scaled)
y_pred_test = elastic.predict(X_test_scaled)

In [76]:
result_MAE.loc[len(result_MAE)] = ['ElasticNet RandomizedSearch MinMaxScaler', mae(y_train, y_pred_train), mae(y_valid, y_pred_valid), mae(y_test, y_pred_test)]
result_RMSE.loc[len(result_RMSE)] = ['ElasticNet RandomizedSearch MinMaxScaler', rmse(y_train, y_pred_train), rmse(y_valid, y_pred_valid), rmse(y_test, y_pred_test)]
result_R2.loc[len(result_R2)] = ['ElasticNet RandomizedSearch MinMaxScaler', r2_score(y_train, y_pred_train), r2_score(y_valid, y_pred_valid), r2_score(y_test, y_pred_test)]

In [77]:
result_MAE

,model,train,valid,test
0,Lasso MinMaxScaler,668.672518,658.821751,665.124980
1,Lasso top10 MinMaxScaler,668.672709,658.822143,665.125393
2,Lasso top10_selection MinMaxScaler,668.672775,658.822322,665.125238
3,Lasso permutation MinMaxScaler,668.673573,658.823407,665.126185
4,Lasso shap MinMaxScaler,668.673568,658.823399,665.126180
5,ElasticNet GridSearch MinMaxScaler,668.851398,658.874139,665.441431
6,ElasticNet RandomizedSearch MinMaxScaler,668.740015,658.850723,665.233957

In [78]:
result_RMSE

,model,train,valid,test
0,Lasso MinMaxScaler,939.338320,914.957220,932.435435
1,Lasso top10 MinMaxScaler,939.338309,914.957361,932.435674
2,Lasso top10_selection MinMaxScaler,939.338320,914.957404,932.435501
3,Lasso permutation MinMaxScaler,939.338313,914.957407,932.435820
4,Lasso shap MinMaxScaler,939.338313,914.957404,932.435822
5,ElasticNet GridSearch MinMaxScaler,939.456763,914.789919,932.780360
6,ElasticNet RandomizedSearch MinMaxScaler,939.348698,914.879394,932.521517

In [79]:
result_R2

                                      model     train     valid      test
0                        Lasso MinMaxScaler  0.578270  0.580479  0.594119
1                  Lasso top10 MinMaxScaler  0.578270  0.580478  0.594118
2        Lasso top10_selection MinMaxScaler  0.578270  0.580478  0.594119
3            Lasso permutation MinMaxScaler  0.578270  0.580478  0.594118
4                   Lasso shap MinMaxScaler  0.578270  0.580478  0.594118
5        ElasticNet GridSearch MinMaxScaler  0.578164  0.580632  0.593818
6  ElasticNet RandomizedSearch MinMaxScaler  0.578261  0.580550  0.594044

In [80]:
def objective(trial, X, y):
    param = {
        'alpha': trial.suggest_float('alpha', 1e-5, 10.0, log=True),
        'l1_ratio': trial.suggest_float('l1_ratio', 0.0, 1.0)
    }
    
    kf = KFold(n_splits=5)
    scores = []

    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model = ElasticNet(**param, random_state=42)
        model.fit(X_train, y_train)
        
        y_pred = model.predict(X_test)
        scores.append(r2_score(y_test, y_pred))

    return np.mean(scores)

In [81]:
study = optuna.create_study(direction='maximize')
study.optimize(lambda trial: objective(trial, X_train_scaled, y_train), n_trials=50)

print(f"Лучший R2 на кросс-валидации: {study.best_value:.4f}")
print(f"Лучшие параметры: {study.best_params}")

[I 2025-12-25 19:47:40,255] A new study created in memory with name: no-name-f768b725-ef1a-42ef-98e4-feed174939c4
[I 2025-12-25 19:47:40,318] Trial 0 finished with value: 0.5773954026886846 and parameters: {'alpha': 0.0005324137197160206, 'l1_ratio': 0.06891016951447582}. Best is trial 0 with value: 0.5773954026886846.
[I 2025-12-25 19:47:40,354] Trial 1 finished with value: 0.5660790053590649 and parameters: {'alpha': 0.013847326889260481, 'l1_ratio': 0.046810794995678084}. Best is trial 0 with value: 0.5773954026886846.
[I 2025-12-25 19:47:40,395] Trial 2 finished with value: 0.47346523638058624 and parameters: {'alpha': 0.28869058756959054, 'l1_ratio': 0.761898794234539}. Best is trial 0 with value: 0.5773954026886846.
[I 2025-12-25 19:47:40,430] Trial 3 finished with value: 0.577407120190573 and parameters: {'alpha': 0.004059314183625207, 'l1_ratio': 0.9766016685352547}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,461] Trial 4 finished with value: 0.13977150821503115 and parameters: {'alpha': 0.9958189741911405, 'l1_ratio': 0.09631100464518805}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,497] Trial 5 finished with value: 0.11198278077821852 and parameters: {'alpha': 1.5540539031013123, 'l1_ratio': 0.21723926573722707}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,528] Trial 6 finished with value: 0.5774052457530864 and parameters: {'alpha': 0.00010290069004715084, 'l1_ratio': 0.7345389224539943}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,554] Trial 7 finished with value: 0.03546359169321187 and parameters: {'alpha': 7.443979443241129, 'l1_ratio': 0.37394276633599044}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,586] Trial 8 finished with value: 0.5774056456651521 and parameters: {'alpha': 4.731561341830755e-05, 'l1_ratio': 0.1279793176093853}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,620] Trial 9 finished with value: 0.5546709855529375 and parameters: {'alpha': 0.02898652282940551, 'l1_ratio': 0.2861891957843229}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,656] Trial 10 finished with value: 0.5774045679579455 and parameters: {'alpha': 0.0012408372998766676, 'l1_ratio': 0.9968430485773022}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,693] Trial 11 finished with value: 0.5774045570603933 and parameters: {'alpha': 1.4787479184050501e-05, 'l1_ratio': 0.5512829259982328}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,731] Trial 12 finished with value: 0.5774043206695868 and parameters: {'alpha': 1.1579137420610824e-05, 'l1_ratio': 0.9930986368189513}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,766] Trial 13 finished with value: 0.5773992969183277 and parameters: {'alpha': 0.0009514934502478473, 'l1_ratio': 0.5413164531384368}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,804] Trial 14 finished with value: 0.5774053114076182 and parameters: {'alpha': 0.00011419628449803131, 'l1_ratio': 0.7421336497311892}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,833] Trial 15 finished with value: 0.5205819571729748 and parameters: {'alpha': 0.07038955467140902, 'l1_ratio': 0.4248090610758197}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,866] Trial 16 finished with value: 0.5772035220576959 and parameters: {'alpha': 0.004014967027755852, 'l1_ratio': 0.6093010707968756}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,904] Trial 17 finished with value: 0.5774047480833264 and parameters: {'alpha': 9.048886605438748e-05, 'l1_ratio': 0.867889422377263}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,936] Trial 18 finished with value: 0.5751950093417638 and parameters: {'alpha': 0.006539405202807512, 'l1_ratio': 0.20992780184505877}. Best is trial 3 with value: 0.577407120190573.
[I 2025-12-25 19:47:40,971] Trial 19 finished with value: 0.5774073416699038 and parameters: {'alpha': 0.0002905634557551353, 'l1_ratio': 0.4116446844976966}. Best is trial 19 with value: 0.5774073416699038.
[I 2025-12-25 19:47:41,010] Trial 20 finished with value: 0.577407358049278 and parameters: {'alpha': 0.0004495070850416437, 'l1_ratio': 0.6405834685284073}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,047] Trial 21 finished with value: 0.5774071865121938 and parameters: {'alpha': 0.0003669603478056907, 'l1_ratio': 0.6582206563110601}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,083] Trial 22 finished with value: 0.5774069062089204 and parameters: {'alpha': 0.0002924078512703763, 'l1_ratio': 0.6541619027747352}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,121] Trial 23 finished with value: 0.5774073382312117 and parameters: {'alpha': 0.0002842190348876685, 'l1_ratio': 0.45245548334861785}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,154] Trial 24 finished with value: 0.5773717791525254 and parameters: {'alpha': 0.0013683367855259732, 'l1_ratio': 0.4593758108986111}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,191] Trial 25 finished with value: 0.5774051149199269 and parameters: {'alpha': 3.4747982926403334e-05, 'l1_ratio': 0.329708099218797}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,227] Trial 26 finished with value: 0.5774071879551494 and parameters: {'alpha': 0.000231785808384497, 'l1_ratio': 0.4527333929968893}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,260] Trial 27 finished with value: 0.5773599424280571 and parameters: {'alpha': 0.0017374155707028584, 'l1_ratio': 0.5222399192551773}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,296] Trial 28 finished with value: 0.5774048764169943 and parameters: {'alpha': 2.6107976287564442e-05, 'l1_ratio': 0.38950619431243616}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,334] Trial 29 finished with value: 0.5774069752596847 and parameters: {'alpha': 0.0005650866669862152, 'l1_ratio': 0.604112667781814}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,369] Trial 30 finished with value: 0.5774069721730815 and parameters: {'alpha': 0.00014950006952342356, 'l1_ratio': 0.2848285284870191}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,424] Trial 31 finished with value: 0.5774071301247022 and parameters: {'alpha': 0.00023171382164976551, 'l1_ratio': 0.48031102466710573}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,463] Trial 32 finished with value: 0.5774016317005333 and parameters: {'alpha': 0.0007220159515611323, 'l1_ratio': 0.45525335424149566}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,503] Trial 33 finished with value: 0.5643534466864848 and parameters: {'alpha': 0.02210001756082028, 'l1_ratio': 0.3476883627422317}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,538] Trial 34 finished with value: 0.5774047486650365 and parameters: {'alpha': 6.388892415123246e-05, 'l1_ratio': 0.8115539634207994}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,590] Trial 35 finished with value: 0.5774067355993309 and parameters: {'alpha': 0.00025972130365085845, 'l1_ratio': 0.6530788678246826}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,626] Trial 36 finished with value: 0.577377116524201 and parameters: {'alpha': 0.0016402431207827568, 'l1_ratio': 0.5766546793740528}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,670] Trial 37 finished with value: 0.5766946231726994 and parameters: {'alpha': 0.0029016146153423837, 'l1_ratio': 0.011026265527232848}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,706] Trial 38 finished with value: 0.5731612151118357 and parameters: {'alpha': 0.012422167351933085, 'l1_ratio': 0.40442909911737424}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,741] Trial 39 finished with value: 0.5773976709358235 and parameters: {'alpha': 0.000568989051275077, 'l1_ratio': 0.1873042442917502}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,778] Trial 40 finished with value: 0.5121090502879431 and parameters: {'alpha': 0.06391395180189761, 'l1_ratio': 0.2899321295776137}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,812] Trial 41 finished with value: 0.5774071677048147 and parameters: {'alpha': 0.0003455889079304576, 'l1_ratio': 0.6427142909962865}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,869] Trial 42 finished with value: 0.5774067721517301 and parameters: {'alpha': 0.00018761119888113047, 'l1_ratio': 0.5057696424007995}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,904] Trial 43 finished with value: 0.5774072984195776 and parameters: {'alpha': 0.0004672439094735005, 'l1_ratio': 0.699316496816149}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,951] Trial 44 finished with value: 0.577405377317582 and parameters: {'alpha': 5.5234385157667336e-05, 'l1_ratio': 0.423813429901411}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:41,986] Trial 45 finished with value: 0.5774067870733075 and parameters: {'alpha': 0.0022822380634792646, 'l1_ratio': 0.8931854488730633}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:42,028] Trial 46 finished with value: 0.5774045282987241 and parameters: {'alpha': 1.928493525512499e-05, 'l1_ratio': 0.6986753891353642}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:42,064] Trial 47 finished with value: 0.5773175226814935 and parameters: {'alpha': 0.005469001400442272, 'l1_ratio': 0.8013661779132328}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:42,104] Trial 48 finished with value: 0.5774059334710319 and parameters: {'alpha': 0.00012226740313531524, 'l1_ratio': 0.5748084835059865}. Best is trial 20 with value: 0.577407358049278.
[I 2025-12-25 19:47:42,151] Trial 49 finished with value: 0.5774072451280616 and parameters: {'alpha': 0.000455708232811711, 'l1_ratio': 0.7103324515428127}. Best is trial 20 with value: 0.577407358049278.

Лучший R2 на кросс-валидации: 0.5774
Лучшие параметры: {'alpha': 0.0004495070850416437, 'l1_ratio': 0.6405834685284073}